export const colorOptions = [
  { value: "#3b82f6", label: "Blue" },
  { value: "#ef4444", label: "Red" },
  { value: "#10b981", label: "Green" },
  { value: "#f59e0b", label: "Yellow" },
  { value: "#8b5cf6", label: "Purple" },
  { value: "#ec4899", label: "Pink" },
  { value: "#06b6d4", label: "Cyan" },
  { value: "#f97316", label: "Orange" },
  { value: "#64748b", label: "Gray" },
  { value: "#84cc16", label: "Lime" },
  { value: "#0ea5e9", label: "Sky" },
  { value: "#a855f7", label: "Violet" },
  { value: "#d946ef", label: "Fuchsia" },
  { value: "#14b8a6", label: "Teal" },
  { value: "#22c55e", label: "Emerald" },
  { value: "#eab308", label: "Amber" },
  { value: "#facc15", label: "Gold" },
  { value: "#dc2626", label: "Crimson" },
  { value: "#2563eb", label: "Indigo" },
  { value: "#9ca3af", label: "Silver" },
  { value: "#f87171", label: "Coral" },
  { value: "#fb7185", label: "Rose" },
];
