import {
  BusFront,
  ShieldPlus,
  BookOpen,
  ShoppingBasket,
  Pizza,
  Boxes,
  HandCoins,
  BanknoteArrowUp,
  Clapperboard,
  CreditCard,
  WalletMinimal,
  Gem,
} from "lucide-react";
export const icons = [
  {
    transportation: <BusFront />,
    healthcare: <ShieldPlus />,
    education: <BookOpen />,
    shopping: <ShoppingBasket />,
    dining: <Pizza />,
    utilities: <Boxes />,
    entertainment: <Clapperboard />,
    salary: <WalletMinimal />,
    bonus: <BanknoteArrowUp />,
    freelance: <CreditCard />,
    investment: <Gem />,
    other: <HandCoins />,
  },
];
